### ISSUE TITLE
How to make background white (not transparent)

### ISSUE THREAD

**Issue by phatpaul** [Collaborne/gulp-mobile-icons#8]
My icon should have a solid white background.  But the generated png has transparent background.

**Comment by ankon** [comment]
We're basically invoking svg2png, without any special background handling. Looking at their issue tracker and guessing a bit: Either the svg is missing an explicit configuration of the background (i.e. it looks white in your editor, but there is actually no background defined), OR you may need to add an additional white rectangle behind your foreground to produce a "background".

I'll close this; if you indeed think that this is a bug in how we manipulate the image please consider filing a PR with a fix.
